language: python
python:
- 3.6
cache:
- apt
env:
  global:
  - secure: Z+nLaN8YU/EyH4awYb/PQyDb4z3sw5lVTJV0L6M5JY/JxOZJn6vThDmQ9bW4S4aeXVc8lt4dLcDL3yECJ+jAljTNGYNsP24fl/2w5ZRdmETPgkb4Z17Y0GULZtBw9TBjT7ohebXsxja5VNebWrXDG88eH/7a9w4n+K1RP2TA0XU=
install:
- travis_retry pip install pelican
- travis_retry pip install beautifulsoup4
script:
- make clean
- make DEBUG=1 RELATIVE=1 html
- |
  if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then
    bash travis_deploy.sh
  fi
